---
title: "LLM Fine Tuning-New York Times Comments(2017)"
author: "Francis Lauder"
date: '2026-01-24'
format: 
    html:
        toc: true
        number-sections: false
        toc-location: left
---

# Introduction

Sentiment analysis involves assigning predefined categories to text, We use use our understanding of the emotional intent of words to infer whether a section of text is negative, neutral, or positive. For our project we will predict sentiment using a pre-trained large language model (llm) from Hugging Face which we will fine-tune on our specific data. A pre-trained model is a LLM trained on a broad dataset to learn general patterns. Through this process is where model parameters and weights are learned. This can be a time-consuming process thus by using a pre-trained the heavy lifting has been borne by the authors of the model . This makes it easier to update the weights of the model on specific data to adapt it for specialized tasks. For the fine-tuning we will use a New York Times 2017 dataset of comments already including sentiment labels. This was accomplished in a previous project using the AFINN method. The AFINN method is a rule-based approach which has a dictionary of words and each word has an intensity score ranging from -5 to 5. The overall sentiment score of a text is calculated by summing the intensity scores. Fine-tuning of the pre-trained model is different as it is a machine learning process. We train the model on a training subset of our specific data and evaluate it on a testing subset of our specific data. These models differ from rule-based methods as they do not look at words in isolation; they look at the whole sentence, understand word order, context, and sarcasm. Once the fine-tuning of the pre-trained model is finished, we will use it to predict sentiment of unlabeled comments from the New York Times 2018 dataset.

We will be using the pre-trained cardiffnlp/twitter-roberta-base-sentiment-latest model. The license can be viewed at the link below.

[cardiffnlp license](https://creativecommons.org/licenses/by/4.0/)

# Data Inspection

## Libraries

```{python}
#| code-fold: true
#| code-summary: "Show Code"

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pickle
import sklearn
from sklearn.model_selection import train_test_split


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"



from transformers import pipeline, AutoModel, AutoTokenizer, AutoModelForSequenceClassification, AutoConfig,Trainer, TrainingArguments


```

```{python}
#| eval: true
#| echo: false

import accelerate
from accelerate import Accelerator
import evaluate

```

```{python}
#| eval: true
#| echo: false
#| include: false

from tqdm.auto import tqdm


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


import torch
import torch.nn.functional as F
import torchtext
from datasets import Dataset, DatasetDict





```

We will first check and verify that the gpu is available.

```{python}
#| code-fold: true
#| code-summary: "Show Code"

torch.cuda.is_available()



```

The 'True' output means the gpu is available.

# Data Review

```{python}



```



```{python}
#| eval: false
#| echo: false



file_path = r'C:\Users\fvlau\OneDrive\Documents\nytCommentsFinetuneLLM\\nyt_comments_sentiment17.csv'


```

```{python}
#| eval: false
#| echo: false


nyt_sentiments17=pd.read_csv(file_path)



```

## Data Review

```{python}
#| eval: false
#| echo: false



file_out = open("nyt_sentiments17", "wb")
pickle.dump(nyt_sentiments17, file_out)
file_out.close()


```

```{python}
#| eval: true
#| echo: false

pickle_in = open("nyt_sentiments17", "rb")
nyt_sentiments17 = pickle.load(pickle_in)


```


```{python}
#| code-fold: true
#| code-summary: "Show Code"



print(nyt_sentiments17.shape)



```

The dataset has just under 970,000 rows and 8 columns. 

```{python}
#| code-fold: true
#| code-summary: "Show Code"



nyt_sentiments17.info()



```



```{python}
#| code-fold: true
#| code-summary: "Show Code"


print(nyt_sentiments17.head(2))

```

We used the .info() method to display the column names.  It is important to note that when configuring the pre-trained model, we will need the sentiment column, which is the label name, and the label column which is the numerical representation of the sentiment column. For the pre-trained model we have selected, if both columns are not present in the dataset, training the model will result in an error. In the pre-processing steps we will see why.

```{python}
#| code-fold: true
#| code-summary: "Show Code"




print(nyt_sentiments17.iloc[:,6:8].head(2))


```



```{python}
#| code-fold: true
#| code-summary: "Show Code"

print(nyt_sentiments17["sentiment"].value_counts())


```

```{python}



```



```{python}
#| code-fold: true
#| code-summary: "Show Code"

nyt_sentiments17["sentiment"].value_counts(normalize=True).round(2).plot(kind='bar')



```

The percentage breakdown of sentiment is negative 43%, positive 42%, and neutral 15%. We will need to keep these percentages during the sampling of the data and splitting it into train, test, and validation sets.

```{python}
#| eval: false
#| echo: false


print(nyt_sentiments17["typeOfMaterial"].value_counts(normalize=True).round(2))


```

```{python}
#| eval: false
#| echo: false



print(nyt_sentiments17["newDesk"].value_counts(normalize=True).round(2))



```

```{python}
#| echo: false
#| eval: false



(pd.crosstab(index=nyt_sentiments17.newDesk, columns=nyt_sentiments17.sentiment, normalize='index').round(2).style.background_gradient(cmap='Blues', axis=None))



```

# Pre-process

## Features

```{python}
#| code-fold: true
#| code-summary: "Show Code"


nyt_sentiments17_2 = nyt_sentiments17.copy()


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

nyt_sentiments17_2.info()


```

We will rename the columns sentiment and commentBody to reflect those used in the pre-trained model

```{python}
#| code-fold: true
#| code-summary: "Show Code"

nyt_comments_dict = {"commentBody":"text", "sentiment":"label_name"}


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

nyt_sentiments17_2 = nyt_sentiments17_2.rename(columns={"clean_comments":"text", "sentiment":"label_name"})



```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

nyt_sentiments17_2.info()



```

Columns not required for fine tuning and prediction will be dropped

```{python}
#| code-fold: true
#| code-summary: "Show Code"


nyt_sentiments17_2=nyt_sentiments17_2.drop(columns=['commentBody','commentID', 'typeOfMaterial', 'newDesk','sentiment_score'], axis=1)

```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

nyt_sentiments17_2.info()


```

```{python}
#| eval: false
#| echo: false


file_out=open("nyt_sentiments17_2", "wb")
pickle.dump(nyt_sentiments17_2, file_out)
file_out.close()


```

```{python}
#| eval: true
#| echo: false

pickle_in = open("nyt_sentiments17_2", "rb")
nyt_sentiments17_2 = pickle.load(pickle_in)


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"




nyt_sentiments17_2[['label','label_name']].value_counts(normalize=True).round(2)


```



Our dataset's sentiment labels now match the pre-trained model.

## Train Test Validation split

Our dataset will be split into training, validation, and testing sets. Before we initiate the split we will sample and shuffle our data.

```{python}
#| eval: false
#| echo: false


nyt_shuffled_small=nyt_sentiments17_2.sample(frac=0.04, random_state=42).reset_index(drop=True)



```

```{python}
#| eval: false
#| echo: false

file_out = open("nyt_shuffled_small", "wb")
pickle.dump(nyt_shuffled_small, file_out)
file_out.close()



```

```{python}
#| eval: true
#| echo: false

pickle_in = open("nyt_shuffled_small", "rb")
nyt_shuffled_small = pickle.load(pickle_in)



```

```{python}
#| eval: false
#| echo: false



nyt_shuffled_medium=nyt_sentiments17_2.sample(frac=0.11, random_state=42).reset_index(drop=True)




```

```{python}
#| eval: false
#| echo: false


file_out = open("nyt_shuffled_medium", "wb")
pickle.dump(nyt_shuffled_medium, file_out)
file_out.close()



```

```{python}
#| eval: true
#| echo: false



pickle_in = open("nyt_shuffled_medium", "rb")
nyt_shuffled_medium = pickle.load(pickle_in)


```

 

```{python}
#| code-fold: true
#| code-summary: "Show Code"
#| eval: false



nyt_shuffled_large = nyt_sentiments17_2.sample(frac=0.25, random_state=42).reset_index(drop=True)


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"
#| eval: false



nyt_shuffled_large = nyt_shuffled_large.dropna()


```

```{python}
#| eval: false
#| echo: false


file_out = open("nyt_shuffled_large", "wb")
pickle.dump(nyt_shuffled_large, file_out)
file_out.close()


```

```{python}
#| eval: true
#| echo: false



pickle_in = open("nyt_shuffled_large", "rb")
nyt_shuffled_large = pickle.load(pickle_in)



```

```{python}
#| code-fold: true
#| code-summary: "Show Code"



nyt_shuffled_large.info()



```


```{python}
#| code-fold: true
#| code-summary: "Show Code"



nyt_shuffled_large[['label', 'label_name']].value_counts(normalize=True).round(2)


```

The sampled data has 242,413 rows.  The sentiment percentage distribution is consistant with the original dataset. 


```{python}





```


70% of the comments will be used for the training set, 10% for the validation set, and the remaining %20 for the testing set.

```{python}
#| code-fold: true
#| code-summary: "Show Code"
#| echo: false



train, test = train_test_split(nyt_shuffled_large, test_size=0.3, stratify=nyt_shuffled_large['label_name'])

test, validation = train_test_split(test, test_size=1/3, stratify=test['label_name'])



```

```{python}
#| eval: false
#| echo: false

file_out = open("train", "wb")
pickle.dump(train, file_out)
file_out.close()


```

```{python}
#| eval: true
#| echo: false


pickle_in = open("train", "rb")
train = pickle.load(pickle_in)


```

```{python}
#| eval: false
#| echo: false


file_out = open("test", "wb")
pickle.dump(test, file_out)
file_out.close()

```

```{python}
#| eval: true
#| echo: false

pickle_in = open("test", "rb")
test = pickle.load(pickle_in)



```

```{python}
#| eval: false
#| echo: false


file_out = open("validation", "wb")
pickle.dump(validation, file_out)
file_out.close()


```

```{python}
#| eval: true
#| echo: false


pickle_in = open("validation", "rb")
validation = pickle.load(pickle_in)


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


train_shape=train.shape
test_shape= test.shape
validation_shape=validation.shape


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


print(f"Train Set Shape: {train_shape}, Test Set Shape: {test_shape} Validation Set Shape: {validation_shape}")



```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

print("Train set sentiment percentage values: \n",train['label_name'].value_counts(normalize=True).round(2))

```

```{python}
#| code-fold: true
#| code-summary: "Show Code"



print("Test set sentiment percentage values: \n",test['label_name'].value_counts(normalize=True).round(2))


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

print("Validation set sentiment percentage values: \n",validation['label_name'].value_counts(normalize=True).round(2))


```

## Dataset

 The format of our data must be compatible with the transformers from Hugging Face, This can be done by using the DatasetDict function which creates a dictionary-like container. We will use it to hold our train, test, and validation splits.

```{python}
#| code-fold: true
#| code-summary: "Show Code"
#| eval: false



dataset = DatasetDict(
    {'train':Dataset.from_pandas(train, preserve_index=False),
    'test':Dataset.from_pandas(test, preserve_index=False),
    'validation':Dataset.from_pandas(validation, preserve_index=False)}
)




```

```{python}
#| eval: false
#| echo: false


file_out = open("dataset", "wb")
pickle.dump(dataset, file_out)
file_out.close()


```

```{python}
#| eval: true
#| echo: false

pickle_in = open("dataset", "rb")
dataset = pickle.load(pickle_in)



```

```{python}
#| code-fold: true
#| code-summary: "Show Code"



type(dataset)


```



```{python}
#| code-fold: true
#| code-summary: "Show Code"


dataset

```

The dataset has a dictionary structure in wich  the train, test,validation splits are the names of the keys and the values are features: text, label_name, and label.

```{python}
#| code-fold: true
#| code-summary: "Show Code"

print(dataset['train'][0])


```

Filtering on the train key and first values we see the text, label_name, and label.

## Tokenize

Tokenization breaks text into manageable units or tokens. Tokenization helps pre-process text data, simplifying tasks such as filtering out punctuation, converting to lowercase, and handling special characters. It also transforms text into numerical IDs which transformers and LLMs require. Tokenization has different methods such as splitting text into individual words,splitting words into sub-words, and breaking text into individual characters. For our model we will split our data into individual words.

```{python}
#| code-fold: true
#| code-summary: "Show Code"


tokenizer = AutoTokenizer.from_pretrained("cardiffnlp/twitter-roberta-base-sentiment-latest")


```


We will create a function that will will transform the text in the dataset to tokens. 

batch['text'] - all individual comments are grouped together for simultaneous processing by the tokenizer. 

padding=max-length - shoter sequences, each row of comments, will be padded up to the maximum length set by the mdoel. 

truncation=True - text sequences, each row of comments, that exceed the maximum length (input length) allowed by the model will be shortened. 

truncation

```{python}
#| code-fold: true
#| code-summary: "Show Code"


def tokenize(batch):
    temp = tokenizer(batch['text'], padding="max_length", truncation=True, max_length=514)
    return temp



```






Using the .map method we will apply the tokenize function to the dataset.



```{python}
#| code-fold: true
#| code-summary: "Show Code"
#| eval: false


sentiment_encoded = dataset.map(tokenize, batched=True, batch_size=None)


```

```{python}
#| eval: false
#| echo: false



file_out = open("sentiment_encoded", "wb")
pickle.dump(sentiment_encoded, file_out)
file_out.close()


```

```{python}
#| eval: true
#| echo: false


pickle_in = open("sentiment_encoded", "rb")
sentiment_encoded = pickle.load(pickle_in)



```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


sentiment_encoded



```

There are now two new columns in data dictionary: input_ids and attention_mask.

attention_mask are binary values (0s and 1s) used to tell the model which tokens in a sequence should be processed and which should be ignored.

1: The token is a real token and should be attended to.
0: The token is a padding token and should be ignored. 

Recall that our tokenizer function padded sequences (comments) so their lengths equaled the maximum length set by the model.  We'll use an example to show how this is displayed. 




```{python}
#| code-fold: true
#| code-summary: "Show Code"


sentence_1="what is an attention mask"
sentence_2="what is padding"


```

```{python}
#| code-fold: true
#| code-summary: "SHow Code"


print(f"Sensentence 1:\n{sentence_1}")


```


```{python}
#| code-fold: true
#| code-summary: "Show Code"




print(f"Sensentence 2:\n{sentence_2}")


```

```{python}
#| code-fold: true
#| code-summary: "SHow Code"



sentence_1_words=sentence_1.split()
sentence_1_word_count=len(sentence_1_words)

```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

sentence_2_words=sentence_2.split()
sentence_2_word_count=len(sentence_2_words)




```



Two sentences of different lengths. 

```{python}
#| code-fold: true
#| code-summary: "Show Code"

print(f"Word count sentence 1: {sentence_1_word_count}, word count sentence 2: {sentence_2_word_count}")


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

text_tokenized=tokenizer([sentence_1, sentence_2], padding=True, return_tensors="pt")



```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

print("Tokenized sentences attention mask:",format(text_tokenized['attention_mask']))


```




From the output it can be seen that the second list represents the shorter sentence.  The 0s tell the model to ignore the padding, ensuring it only considers  "what", "is", "padding".





```{python}
#| code-fold: true
#| code-summary: "SHow Code"


print("Attention mask first row of training data:\n",sentiment_encoded['train'][1]['attention_mask'])


```

We observe how the attention mask looks like from one row of the training data. 

```{python}





```

input_ids are the tokenized text.

Let's compare a row of the text column and the new input_ids columns.

```{python}
#| code-fold: true
#| code-summary: "Show Code"


print(sentiment_encoded['train'][0]['text'])


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


print(sentiment_encoded['train'][0]['input_ids'][1:17])


```

The first output is the original text from the first row of the training split. From the second output we have a list, which are the tokens assigned to the words from the text column.

## Labels

There is one last step needed to prepare our data. As will be seen later when setting up the configuration, the model requires two variables: label2id and id2label. This was mentioned when reviewing the initial dataset: the requirement of a label_name column and label column for creating these variables.

```{python}
#| code-fold: true
#| code-summary: "Show Code"



dataset['train'][0]

```

From the output we see the label_name and label columns. We will use dictionary comprehension to create these variables. A dictionay comprehension (similar to list comprehension) is a concise way to .

First, label2id will be created. The dictionary comprehension will create a dictionary with key/value pairs. We will generate the dictionary's keys by transforming Label_name and values are generated by transforming labels from dataset['train'].  Basically, this is mapping label_name to label.

```{python}
#| code-fold: true
#| code-summary: "Show Code"

label2id = {x['label_name']:x['label'] for x in dataset['train']}


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


label2id.items()

```

```{python}
#| eval: false
#| echo: false


label2id

```

label2id has been successfully created as seen in the output.

Now we will use label2id to create id2label. The difference in using dictionary comprehension here is we'll be transforming the a dictionary (label2id) to create a new dictionary.  The transformation is done by by inter-changing key/value pairs so now the keys from label2id become values and values become keys. This results in id2label having label as the key and label_name as the values.

```{python}
#| code-fold: true
#| code-summary: "Show Code"

id2label = {v:k for  k,v in label2id.items()}


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

id2label.items()


```

```{python}
#| eval: false
#| echo: false

id2label


```

# Model Fine Tuning

We will create a model checkpoint which is simply the chosen pre-trined Hugging Face model. Creating the model_checkpoint object makes it easier to apply the model in our process steps.

```{python}
#| code-fold: true
#| code-summary: "Show Code"



model_checkpoint = "cardiffnlp/twitter-roberta-base-sentiment-latest"


```

```{python}
#| eval: false
#| echo: false



torch.backends.cudnn.deterministic=True
RANDOM_SEED=123
#torch.manual_seed(RANDOM_SEED)


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

model = AutoModel.from_pretrained(model_checkpoint)



```

```{python}
#| eval: false
#| echo: false

model



```

```{python}
#| eval: false
#| echo: false
model.config


```

```{python}
#| eval: false
#| echo: false
model.config.id2label


```

```{python}
#| eval: false
#| echo: false

model.config.label2id


```


```{python}
#| code-fold: true
#| code-summary: "Show Code"


device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

config = AutoConfig.from_pretrained(model_checkpoint, label2id=label2id, id2label=id2label)

model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, config=config).to(device)





```

The device object is using the gpu if available, If the gpu is not available then the cpu will be used.

For our model configuration we will assign the model's label2id and id2label attributes to the variables of the same name we created. And finally our model object uses the model_checkpoint and config object we created. The to(device) moves the model to the selected device, the gpu in this case.

```{python}
#| code-fold: true
#| code-summary: "Show Code"

device



```

The output shows the device is 'cuda' meaning it is on our gpu.

```{python}
#| code-fold: true
#| code-summary: "Show Code"


model


```



```{python}
#| code-fold: true
#| code-summary: "Show Code"


model.config


```

id2label

```{python}
#| code-fold: true
#| code-summary: "Show Code"

model.config.id2label

```

label2id

```{python}
#| code-fold: true
#| code-summary: "Show Code"

model.config.label2id


```




From the model configuration we see the label2id and id2label variables that we needed to create for the model.


## Metrics

```{python}
#| eval: false
#| echo: false


accuracy = evaluate.load("accuracy")
precision = evaluate.load("precision")
recall = evaluate.load("recall")
f1 = evaluate.load("f1")


```

```{python}
#| eval: false
#| echo: false


accuracy.features

```

```{python}
#| eval: false
#| echo: false



def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    accuracy=accuracy.compute(predictions=predictions, references=labels)["accuracy"]
    precision=precision.compute(predictions=predictions, references=labels)["precision"]
    recall=recall.compute(predictions=predictions, references=labels)["recall"]
    f1=f1.compute(predictions=predictions, references=labels)["f1"]
    return {"accuracy":accuracy, "precision":precision, "recall":recall, "f1":f1}


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score




```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)

    acc = accuracy_score(labels, preds)
    prec = precision_score(labels, preds, average='weighted')
    rec = recall_score(labels, preds, average='weighted')
    f1 = f1_score(labels, preds, average='weighted')

    return {"accuracy": acc, "precision": prec, "recall": rec, "f1": f1}




```

The function creates the computation of our selected metrics forf use during the model evaluation on our validation set.

Metric definition:

• Accuracy-measures the number of predictions that are correct as a percentage of the total number of predictions that are made. As an example, if 90% of your predictions are correct, your accuracy is simply 90%. Calculation: number of correct predictions/Number of total predictions. TP+TN/(TP+TN+FP+FN)

• Precision-tells us about the quality of positive predictions. It may not find all the positives but the ones that the model does classify as positive are likely to be correct. As an example, out of everyone predicted to have defaulted, how many of them did default? So, within everything that has been predicted as positive, precision counts the percentage that is correct. Calculation: True positives/All Positives. TP/(TP+FP)

• Recall- tells us about how well the model identifies true positives. The model may find a lot of positives, yet it also will incorrectly detect many positives that are not actually positives. Out of all the patients who have the disease, how many were correctly identified? So, within everything that is positive, how many did the model successfully find? A model with low recall is unable to find all (or a large part) of the positive cases in the data. Calculated as: True Positives/ (False Negatives + True Positives)

• F1 Score-The F1 score is defined as the harmonic mean of precision and recall. The formula for the F1 score is the following: 2 times(precision\*Recall)/ (Precision + Recall)) Since the F1 score is an average of Precision and Recall, it means that the F1 score gives equal weight to Precision and Recall.

```{python}
#| eval: true
#| echo: false


accelerator=Accelerator()


```

## Configure Training Arguments

```{python}
#| code-fold: true
#| code-summary: "Show Code"



training_args = TrainingArguments(
    output_dir="./results",
    overwrite_output_dir=True,
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=2,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_first_step=10,
    save_steps=500,
    disable_tqdm=False,
    metric_for_best_model='eval_loss',
    load_best_model_at_end=True


)


```

Training Arguments:

-   Output_dir: the directory where we will store the results of the model.

-   overwrite_ouput_dir: When set to true, the output directory is overwritten on a new training of the model.

-   eval_strategy: The interval for evaluating the model. For our training we have set it to evaluate after each epoch*.

-   save_strategy: How often to save the model. We have set it to after each epoch.

-   learning_rate: controls how quickly the model's parameters move towards the optimal solution (minimizing the loss function)

-   per_device_train_batch: subset of the entire training dataset. It is the number of samples processed before the model is updated. per_device_eval_batch_size: is the number of samples processed before the model is evaluated.

-   weight_decay: used to discourage model from using large weight values during training. Prevents overfitting.

-   logging_dir: directory where the logs are saved.

-   save_steps: Determines how frequently the model's checkpoint is saved during training.

*An epoch is a training iteration during which we update the paramters for all our training samples.

```{python}
#| eval: false
#| echo: false


#tokenizer=tokenizer)deprecated

```




## Trainer

Set up the trainer

```{python}
#| code-fold: true
#| code-summary: "Show Code"



trainer = Trainer(model=model, args=training_args,
                  compute_metrics=compute_metrics,
                  train_dataset=sentiment_encoded['train'],
                  eval_dataset=sentiment_encoded['validation'],
                  processing_class=tokenizer)


```

We can now fine tune the model.

```{python}
#| code-fold: true
#| code-summary: "Show Code"
#| eval: false


trainer.train()


```

A loss function tells us how good our model is at making predictions during training by helping us assess the differences between actual values and those predicted by the model. The lower the loss function the better our model is.


After 2nd epoch eval loss 0.15 and training loss0.156.  after 3rd epock eval loss 0.1646 and training loss .129/0.22


```{python}
#| eval: false
#| echo: false

eval_rersults_4 = trainer.evaluate()





```

```{python}
#| eval: false
#| echo: false


file_out = open("eval_results_4", "wb")
pickle.dump(eval_rersults_4, file_out)
file_out.close()


```

```{python}
#| eval: true
#| echo: false


pickle_in = open("eval_results_4", "rb")
eval_results_4 = pickle.load(pickle_in)



```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

print(f"Evaluation results 4 epcohs and 2e-5: {eval_results_4}")


```

Our first model was trained on 38,786 rows of data, 4 epochs and a learning rate of 2e-5. The result was a training loss of 0.19 and and a evaluation loss of 0.54. evaluation accuracy, precision, recall, and f1 scores were all around 0.88. Though these scores are not bad the difference between training and evaluation loss is significant and indicates overfitting. We'll train the model with different parameters on the same data.

```{python}
#| eval: true
#| echo: false


eval_results_3 = trainer.evaluate()


```

```{python}
#| eval: false
#| echo: false


file_out = open("eval_results_3", "wb")
pickle.dump(eval_results_3, file_out)
file_out.close()


```

```{python}
#| eval: true
#| echo: false



pickle_in = open("eval_results_3", "rb")
eval_results_3 = pickle.load(pickle_in)



```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


print(f"Evaluation results 3 epochs and 1e-5 learning rate: {eval_results_3}")



```

This time we changed the number of epochs to 3 and reduced the learning rate to 1e-5. The result was a training loss loss of 0.325 and an evaluation loss of 0.40. Though the evaluation loss was lower, the training loss significantly increased. We would like to have loss scores below 0.2. Additionally, accuracy, precision, recall, and f1 scores dropped to around 0.85. Lowering the learning rate did not have a positive affect on the model. The issue could be our training data is too small, which leads to the model memorizing the training data's specific patterns which causes the model to generalize to new data.

```{python}
#| eval: false
#| echo: false


eval_results_medium = trainer.evaluate()


```

```{python}
#| eval: false
#| echo: false


file_out = open("eval_results_medium", "wb")
pickle.dump(eval_results_medium, file_out)
file_out.close()


```

```{python}
#| eval: true
#| echo: false


pickle_in = open("eval_results_medium", "rb")
eval_results_medium = pickle.load(pickle_in)


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

print(f"Evaluation results 11% data sample: {eval_results_medium}")



```

The sample was increased to 11% of the data. The training set is now 106,662 rows. The additional data had a positive impact on the model as training loss dropped to 0.167 and evaluation loss decreased to .024. Accuracy, precision, recall, and f1 scores all increased to around 0.92. These results moved in the right direction though we would like to close the distance between training loss and evaluation loss.



```{python}
#| code-fold: true
#| code-summary: "Show Code"
#| eval: false

eval_results_large = trainer.evaluate()


```

```{python}
#| eval: false
#| echo: false


file_out = open("eval_results_large", "wb")
pickle.dump(eval_results_large, file_out)
file_out.close()



```

```{python}
#| eval: true
#| echo: false



pickle_in = open("eval_results_large", "rb")
eval_results_large = pickle.load(pickle_in)


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


print(f"Evaluation results 25% data and 2 epochs:\n {eval_results_large}")

```

For this round of training we increased the sample to 25% of the data, with 169,688 rows assigned to the training data. The result was a training loss 0.1531 and an evaluation loss of 0.1756. Evaluation accuracy, precision, recall, and f1 scores all improved to around 0.95. Increasing the training data to 169,688 rows provided good results as there is only a 0.022 difference between training and evaluation loss indicating not much over fitting. We achieved our evaluation results on only 2 epochs, though even with one less epoch there was a notable increase in evaluation run tumtime.

## Test Set Metrtics

```{python}
#| code-fold: true
#| code-summary: "Show Code"
#| eval: false

preds_output = trainer.predict(sentiment_encoded['test'])

```

```{python}
#| eval: false
#| echo: false


file_out = open("preds_output", "wb")
pickle.dump(preds_output, file_out)
file_out.close()



```

```{python}
#| eval: true
#| echo: false


pickle_in = open("preds_output", "rb")
preds_output = pickle.load(pickle_in)


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


print("Test set metrics:\n",preds_output.metrics)

```

Predicting on the test set we see that the loss was slightly lower at 0.1725. The other metrics are similar to the evaluation results at around 0.95. This means our model is generalizing well to unseen data.

### Classification Report

In order to create our classification report and confusion matrix we will need to create predicted and actual objects. y_pred is the predictions from our fine-tuned model. You will notice that it is being created from the preds_output object. y_true are the actual outcomes from our original data. You will notice that we are creating the object from the labels of the test set.

```{python}
#| code-fold: true
#| code-summary: "Show Code"

y_pred = np.argmax(preds_output.predictions, axis = 1)

y_true = sentiment_encoded['test'][:]['label']



```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


from sklearn.metrics import classification_report




```

```{python}
#| code-fold: true
#| code-summary: "Show Code"
#| eval: false

test_classification_rpt = classification_report(y_true, y_pred)


```

```{python}
#| eval: false
#| echo: false


file_out = open("test_classification_rpt", "wb")
pickle.dump(test_classification_rpt, file_out)
file_out.close()

```

```{python}
#| eval: true
#| echo: false



pickle_in = open("test_classification_rpt", "rb")
test_classification_rpt = pickle.load(pickle_in)


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"



print("Test set classification report:\n",test_classification_rpt)


```

Using the classification report we can evaluate the test set metrics by label. The metrics show what percentage of the predictions were actually true. The model performs very well on predicting negative sentiment (label 0) and positive sentiment (label 2) with scores ranging from 0.94 to 0.97. The model does not perform as well on predicting neutral sentiment (label 1) with scores ranging from 0.81 to 086.  These are still good scores; just not at the level of the other labels. The model is good at accuratley predicting neutral sentiment, it's just not strong in finding neutral sentiment as seen in the .05 difference between precision and recall scores.

```{python}






```

### Confusion Matrix

```{python}




```

The confusion matrix is a visual representation of how our model performed on predicting on the test set. It shows how many predictions were correct (True Negatives/Neutrals/Positives,) versus incorrect (False Negatives/Neutrals) when compared to actual outcomes.

```{python}
#| code-fold: true
#| code-summary: "Show Code"


from sklearn.metrics import confusion_matrix

```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

cm=confusion_matrix(y_true, y_pred)

plt.figure(figsize=(5,5))
sns.heatmap(cm, annot = True, xticklabels=label2id.keys(), yticklabels=label2id.keys(), fmt='d',  cmap='Reds')
plt.ylabel("Actual")
plt.xlabel("Predicted")

#cbar=False,

```

```{python}
#| eval: false
#| echo: false


plt.show()

```

Let's interpret the confusion matrix. The target variable has three values: Negative, Neutral, or Positive The columns represent the actual values of the target variable The rows represent the predicted values of the target variable.

Terms for confusion matrix:

We should note that most confusion matrices have just a positive and negative class. Our model has three classes with neutral being the additional class.

True Positive (TP)

```         
The predicted value matches the actual value.
The actual value was positive, and the model predicted a positive value.
```

True Negative (TN)

```         
The predicted value matches the actual value
The actual value was negative, and the model predicted a negative value.
```

True Neutral (TL)

```         
The predicted value matches the actual value
The actual value was neutral, and the model predicted a neutral value.
```

False Positive (FP)

```         
The predicted value was falsely predicted.
The actual value was negative or neutral, but the model predicted a  positive value.
```

False Negative (FN)

```         
The predicted value was falsely predicted.
The actual value was neutral or positive, but the model predicted a negative value.
```

False Neutral (FL)

```         
The predicted value was falsely predicted.
The actual value was negative or positive, but the model predicted a neutral value.
```

Appyling these terms to our confusion matrix we find:

True Negative (TN) = 16,249, meaning our model correctly classified 16,249 negative class data points. True Neutral (TL) = 4,720, meaning our model correctly classified 4,720 neutral class data points. True Positive (TP) = 15,543, meaning our model correctly classified 15,543 positve class data points. False Negative (FN) = 432, meaning the model incorrectly classified 275 neutral and 157 positive class data points as belonging to the negative class. False Neutral (FL) = 1,077, meaning the model incorrectly classified 685 negative and 392 positive class data points as belonging to the neutral class. False Positive (FP) = 765, meaning the model incorrectly classified 296 negative and 469 neutral class data points as belonging to the negative class.

We can put these numbers in perspective by using percentages for total predictions for each class.

Of the total predictions for the negative class, 97.4% were correctly predicted as the negative class, 1.7% were incorrectly predicted as the neutral class and less than 1% were incorrectly predicted as the positive class.

Of the total predictions for the neutral class, 81.4% were correctly predicted as the neutral class, 11.8% were incorrectly predicted as the negative class, and 6.8% were incorrectly predicted as the positive class.

Of the total predictions for the positive class, 95.3% were correctly predicted as the positive class,  1.8% were incorrectly predicted as the negative class, and 2.9% were incorrectly predicted as the neutral class.

The insight we gain from these results is the model is excellent at predicting positive and negative sentiment. The model is not as strong at predicting the neutral class though the results are still considered good.

# Predicting on unlabeled data

Now that we have our pre-trained model fine tuned we will use it to predict on a new dataset. The data includes New York Times comments from the 2018 year.

```{python}
#| eval: false
#| echo: false

def get_prediction(text):

    input_encoded = tokenizer(text, return_tensors='pt').to(device)

    with torch.no_grad():
        outputs = model(**input_encoded)

    logits = outputs.logits

    pred = torch.argmax(logits, dim=1).item()
    return id2label[pred]


```

```{python}
#| eval: false
#| echo: false


def get_prediction(text):

    input_encoded = tokenizer(text, return_tensors='pt').to(device)

    with torch.no_grad():
        outputs = model(**input_encoded)

    logits = outputs.logits
    probabilities = torch.nn.functional.softmax(logits, dim=-1)

    pred = torch.argmax(probabilities, dim=-1).item()
    return probabilities, id2label[pred]



```

The fine-tuned model will be saved which allows us to use it for predicting on future data.

```{python}
#| code-fold: true
#| code-summary: "Show Code"
#| eval: false

model.save_pretrained("./results/final_model")
tokenizer.save_pretrained("./results/final_tokenizer")



```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


new_model = AutoModelForSequenceClassification.from_pretrained("./results/final_model")

new_tokenizer = AutoTokenizer.from_pretrained("./results/final_tokenizer")






```

```{python}
#| eval: false
#| echo: false



file_path = r'C:\Users\fvlau\OneDrive\Documents\nytCommentsFinetuneLLM\\nyt_comments18.csv'


```

```{python}
#| eval: false
#| echo: false


nyt_sentiments18=pd.read_csv(file_path)


```

```{python}
#| eval: false
#| echo: false

file_out = open("nyt_sentiments18", "wb")
pickle.dump(nyt_sentiments18, file_out)
file_out.close()


```

```{python}
#| eval: true
#| echo: false



pickle_in = open("nyt_sentiments18", "rb")
nyt_sentiments18 = pickle.load(pickle_in)


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


nyt_sentiments18.info()


```

```{python}
#| eval: false
#| echo: true


nyt_sentiments18=nyt_sentiments18.dropna()


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


new_model.to(device)

```

We are setting the sci_mode (scientific notation) to false for easier interpretaton of probability output.

```{python}
#| code-fold: true
#| code-summary: "Show Code"


torch.set_printoptions(sci_mode=False)


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"




def get_prediction(text):

    """
        Applies fine-tuned model and tokenizer to predict sentiment

        Args: 
            text: A string of text.

        Returns: 
            probabilites: predicted probability of each sentiment. Probabilites sum to 1.
            id2label[pred]: predicted sentiment label.
    """

    input_encoded = new_tokenizer(text, return_tensors='pt').to(device)

    with torch.no_grad():
        outputs = new_model(**input_encoded)

    logits = outputs.logits
    probabilities = torch.nn.functional.softmax(logits, dim=-1)

    pred = torch.argmax(probabilities, dim=-1).item()
    return probabilities, id2label[pred]


```

We created a function that will take in a string of text and return the probabilities of the predicted sentiments and the predicted sentiment label with the highest probability. Probabilty is the confidence we have in predicted label.

For comparison, we will print the text string predicted along with the model output.

```{python}
#| code-fold: true
#| code-summary: "Show Code"


print("Comment:",nyt_sentiments18.iloc[50,0])
print("Type of Material:",nyt_sentiments18.iloc[50,4])
print("News Desk:",nyt_sentiments18.iloc[50,3])
print(get_prediction(nyt_sentiments18.iloc[50,0]))

```

Here the prediction is negative and a high confidence in the prediction with a probability of 0.9999.

```{python}
#| code-fold: true
#| code-summary: "Show Code"


print("Comment:",nyt_sentiments18.iloc[100,0])
print("Type of Material:",nyt_sentiments18.iloc[100,4])
print("News Desk:",nyt_sentiments18.iloc[100,3])
get_prediction(nyt_sentiments18.iloc[100,0])



```

```{python}
#| eval: false
#| echo: false

print("Comment:",nyt_sentiments18.iloc[200,0])
print("Type of Material:",nyt_sentiments18.iloc[200,4])
print("News Desk:",nyt_sentiments18.iloc[200,3])
get_prediction(nyt_sentiments18.iloc[200,0])


```



```{python}
#| code-fold: true
#| code-summary: "Show Code"


print("Comment:",nyt_sentiments18.iloc[240,0])
print("Type of Material:",nyt_sentiments18.iloc[240,4])
print("News Desk:",nyt_sentiments18.iloc[240,3])
get_prediction(nyt_sentiments18.iloc[240,0])


```

The prediction for this comment is neutral.

```{python}
#| code-fold: true
#| code-summary: "Show Code"

print("Comment:",nyt_sentiments18.iloc[310,0])
print("Type of Material:",nyt_sentiments18.iloc[310,4])
print("News Desk:",nyt_sentiments18.iloc[310,3])
get_prediction(nyt_sentiments18.iloc[310,0])


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


print("Comment:",nyt_sentiments18.iloc[410,0])
print("Type of Material:",nyt_sentiments18.iloc[100,4])
print("News Desk:",nyt_sentiments18.iloc[410,3])
get_prediction(nyt_sentiments18.iloc[421,0])

```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


print("Comment:",nyt_sentiments18.iloc[510,0])
print("Type of Material:",nyt_sentiments18.iloc[510,4])
print("News Desk:",nyt_sentiments18.iloc[510,3])
get_prediction(nyt_sentiments18.iloc[510,0])


```

```{python}
#| code-fold: true
#| code-summary: "Show Code"


print("Comment:",nyt_sentiments18.iloc[540,0])
print("Type of Material:",nyt_sentiments18.iloc[540,4])
print("News Desk:",nyt_sentiments18.iloc[540,3])
get_prediction(nyt_sentiments18.iloc[540,0])



```

```{python}
#| code-fold: true
#| code-summary: "Show Code"

print("Comment:",nyt_sentiments18.iloc[588,0])
print("Type of Material:",nyt_sentiments18.iloc[588,4])
print("News Desk:",nyt_sentiments18.iloc[588,3])
get_prediction(nyt_sentiments18.iloc[588,0])


```

```{python}
#| eval: false
#| echo: false


print("Comment:",nyt_sentiments18.iloc[623,0])
print("Type of Material:",nyt_sentiments18.iloc[623,4])
print("News Desk:",nyt_sentiments18.iloc[623,3])
get_prediction(nyt_sentiments18.iloc[623,0])


```

```{python}
#| eval: true
#| echo: false



print("Comment:",nyt_sentiments18.iloc[10000,0])
print("Type of Material:",nyt_sentiments18.iloc[10000,4])
print("News Desk:",nyt_sentiments18.iloc[10000,3])
get_prediction(nyt_sentiments18.iloc[10000,0])



```


```{python}
#| eval: true
#| echo: false


print("Comment:",nyt_sentiments18.iloc[30000,0])
print("Type of Material:",nyt_sentiments18.iloc[30000,4])
print("News Desk:",nyt_sentiments18.iloc[30000,3])
get_prediction(nyt_sentiments18.iloc[30000,0])




```

```{python}
#| eval: true
#| echo: false


print("Comment:",nyt_sentiments18.iloc[40000,0])
print("Type of Material:",nyt_sentiments18.iloc[40000,4])
print("News Desk:",nyt_sentiments18.iloc[40000,3])
get_prediction(nyt_sentiments18.iloc[40000,0])



```



```{python}
#| eval: false
#| echo: false


print("Comment:",nyt_sentiments18.iloc[60000,0])
print("Type of Material:",nyt_sentiments18.iloc[60000,4])
print("News Desk:",nyt_sentiments18.iloc[60000,3])
get_prediction(nyt_sentiments18.iloc[60000,0])




```

```{python}
#| eval: false
#| echo: false



print("Comment:",nyt_sentiments18.iloc[110000,0])
print("Type of Material:",nyt_sentiments18.iloc[110000,4])
print("News Desk:",nyt_sentiments18.iloc[110000,3])
get_prediction(nyt_sentiments18.iloc[110000,0])




```

```{python}
#| eval: false
#| echo: false



print("Comment:",nyt_sentiments18.iloc[280000,0])
print("Type of Material:",nyt_sentiments18.iloc[280000,4])
print("News Desk:",nyt_sentiments18.iloc[280000,3])
get_prediction(nyt_sentiments18.iloc[280000,0])




```


```{python}
#| eval: true
#| echo: false




print("Comment:",nyt_sentiments18.iloc[390000,0])
print("Type of Material:",nyt_sentiments18.iloc[390000,4])
print("News Desk:",nyt_sentiments18.iloc[390000,3])
get_prediction(nyt_sentiments18.iloc[390000,0])



```

```{python}
#| eval: true
#| echo: false




print("Comment:",nyt_sentiments18.iloc[500000,0])
print("Type of Material:",nyt_sentiments18.iloc[500000,4])
print("News Desk:",nyt_sentiments18.iloc[500000,3])
get_prediction(nyt_sentiments18.iloc[500000,0])

```

```{python}
#| eval: false
#| echo: false


print("Comment:",nyt_sentiments18.iloc[580000,0])
print("Type of Material:",nyt_sentiments18.iloc[580000,4])
print("News Desk:",nyt_sentiments18.iloc[580000,3])
get_prediction(nyt_sentiments18.iloc[580000,0])



```


```{python}
#| eval: false
#| echo: false



print("Comment:",nyt_sentiments18.iloc[750000,0])
print("Type of Material:",nyt_sentiments18.iloc[750000,4])
print("News Desk:",nyt_sentiments18.iloc[750000,3])
get_prediction(nyt_sentiments18.iloc[750000,0])


```

```{python}
#| eval: true
#| echo: false



print("Comment:",nyt_sentiments18.iloc[800000,0])
print("Type of Material:",nyt_sentiments18.iloc[800000,4])
print("News Desk:",nyt_sentiments18.iloc[800000,3])
get_prediction(nyt_sentiments18.iloc[800000,0])


```

From a our randomly selected  sample of comments we find mostly high confidence in the models predictions. 

# Using fine-tuned model

Our fine-tuned model can be used in a number of ways. We can build an application with our model on a platform such as Streamlit, which will allow users to have a user interface to upload text for sentiment prediction. Our model can also be used as part of an AI Agent.